### PR TITLE
Swap - Custom Token Address

### PR DESCRIPTION
**Pull request by agbanusi**
## Description
Make user list customizable by saving tokenList in local Storage but that will only be done if token exist in jupiter and it is searched by token address to ensure that tokens with similar names/spellings don't save and fill up space in the token list dropdown.

I also added ETH, SRM, GMT and mSOL to token list for GooseFx

Only thing left is a default token picture for unknown tokens like the question mark picture or so

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] The related ClickUp task has been linked to this PR
- [x] The person creating the pull request is listed in "Assignees"
- [x] My code follows the code style of this project .
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Screenshots or Loom Video (if appropriate):
https://www.loom.com/share/468f13e83a1a4f1f841e496c2aaa530c

### CODE REVIEW

**Comment by usgoose** [comment]
Task linked: [CU-2xw4kgg UI:Swap - add paste address feature and bring up token if exists in Jupiter sdk](https://app.clickup.com/t/2xw4kgg)

**Comment by usgoose** [comment]
What about GMT?

**Comment by agbanusi** [comment]
> What about GMT?

GMT does not seem to appear in Jupiter's token list

**Comment by agbanusi** [comment]
> What about GMT?

Had issue with four tokens having same symbol GMT but working on a blacklist feature for the rest of them

Screenshot 2022-06-02 at 19 32 31

**Review by walt-1 — APPROVED** [review]

**Pull request merged**
