### PR TITLE
Rewards Upkeep

### PR DESCRIPTION
**Pull request by deadeagle63**
Numeros

## Description
Fixes a bunch of requests:
- Timer for next reward claim
- Approx value you get everyday
- Approx value tooltip for staked/wallet balance
- APY introduction
- DEV: two new hooks, useBoolean, useTimer

## How has this been tested?
Feature branch.
## Types of changes

- [ ] Technical Debt (non-breaking change which removes unused code/assets)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] The related ClickUp task has been linked to this PR
- [x] The person creating the pull request is listed in "Assignees"
- [ ] Change requires updated documentation

### CODE REVIEW

**Comment by deadeagle63** [comment]
Task linked: [CU-86ctyvq6m Rewards Timer](https://app.clickup.com/t/86ctyvq6m)

**Comment by deadeagle63** [comment]
Task linked: [CU-86ctyvq7c Rewards APY](https://app.clickup.com/t/86ctyvq7c)

**Comment by deadeagle63** [comment]
Task linked: [CU-86ctyvq96 Rewards Tooltip](https://app.clickup.com/t/86ctyvq96)

**Comment by deadeagle63** [comment]
Task linked: [CU-86ctyvq9q Add staked % to rewards](https://app.clickup.com/t/86ctyvq9q)

**Review by walt-1 — APPROVED** [review]

**Review by walt-1 — APPROVED** [review]

**Pull request merged**
