### PR TITLE
Feature/admin creator

### PR DESCRIPTION
**Pull request by candidatek**
## Types of changes

- [ ] Technical Debt (non-breaking change which removes unused code/assets)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] The related ClickUp task has been linked to this PR
- [x] The person creating the pull request is listed in "Assignees"
- [ ] Change requires updated documentation

### CODE REVIEW

**Comment by walt-1** [comment]
@skshriharik is this branch still needed? If not please delete after merging to dev.

**Comment by usgoose** [comment]
Task linked: [CU-2hrbh3c API: NFT LP Admin pages](https://app.clickup.com/t/2hrbh3c)

**Comment by walt-1** [comment]
@skshriharik also is this the correct clickup task?

**Comment by usgoose** [comment]
Task linked: [CU-2ft8q4z UI: NFT Creator Pages](https://app.clickup.com/t/2ft8q4z)

**Pull request merged**
