### PR TITLE
Swap: Mobile Responsiveness

### PR DESCRIPTION
**Pull request by agbanusi**
## Description

Using the design given, many updates were made to the mobile view giving mobile users a much more better view of the swap mobile

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] The related ClickUp task has been linked to this PR
- [x] The person creating the pull request is listed in "Assignees"
- [x] My code follows the code style of this project .
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Screenshots or Loom Video (if appropriate):
https://www.loom.com/share/e42436d01db644468ac8e1f6390d7f78

### CODE REVIEW

**Comment by usgoose** [comment]
Task linked: [CU-25dhdfd UI: Swap - Make mobile design](https://app.clickup.com/t/25dhdfd)

**Comment by usgoose** [comment]
Task linked: [CU-2frfuff UI: Swap - "0% cheaper..." Doesn't Change](https://app.clickup.com/t/2frfuff)

**Comment by walt-1** [comment]
Two items that need to be addressed
- The dark/lite mode toggle needs to be at the bottom of the menu that expands, not in the footer
- There are two containers that are scrolling when there should only be one scrolling container, look into setting the height of the most parent container so that the only scrolling is on the swap contents

**Comment by agbanusi** [comment]
> Two items that need to be addressed
> 
> * The dark/lite mode toggle needs to be at the bottom of the menu that expands, not in the footer
> * There are two containers that are scrolling when there should only be one scrolling container, look into setting the height of the most parent container so that the only scrolling is on the swap contents

Fixed

**Review by walt-1 — APPROVED** [review]

**Pull request merged**
