### PR TITLE
General: RPC Health Check

### PR DESCRIPTION
**Pull request by candidatek**
@lukewalt @NAK1998 @Shashank729 @agbanusi   Please have a look on this PR.
## Types of changes

- [ ] Technical Debt (non-breaking change which removes unused code/assets)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] The related ClickUp task has been linked to this PR
- [x] The person creating the pull request is listed in "Assignees"
- [ ] Change requires updated documentation

### CODE REVIEW

**Comment by NAK1998** [comment]
Remove yarn.lock if no new packages are added. Other changes look good!

**Comment by usgoose** [comment]
Task linked: [CU-4735fk4 UI: RPC Health Check](https://app.clickup.com/t/4735fk4)

**Comment by walt-1** [comment]
I have marked this as a work in progress as @skshriharik updates the way data is returning from the healthcheck service

**Comment by candidatek** [comment]
Hey @lukewalt i have addressed the comments please have a look and we can merge this PR.

**Pull request merged**
