### PR TITLE
Update Wallet Adapter

### PR DESCRIPTION
**Pull request by jordaaash**
## Description

This PR updates Wallet Adapter according to https://github.com/solana-labs/wallet-adapter/issues/604. This adds support for the Wallet Standard and updates Mobile Wallet Adapter.

The PR also adds yarn resolutions for `@solana/web3.js` and `react` to avoid multiple versions being resolved.

## How has this been tested?

Building the project locally, opening the wallet modal and seeing Backpack and Glow detected as Standard Wallets, and connecting to Backpack without an adapter.

## Types of changes

- [x] Technical Debt (non-breaking change which removes unused code/assets)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] The related ClickUp task has been linked to this PR
- [ ] The person creating the pull request is listed in "Assignees"
- [ ] Change requires updated documentation

## Screenshots

Backpack and Glow detected as Standard Wallets, so they show up first.
Screen Shot 2022-10-21 at 2 56 49 PM

Connected to Backpack without an adapter.
Screen Shot 2022-10-21 at 2 59 47 PM

### CODE REVIEW

**Comment by walt-1** [comment]
Hi @jordansexton,

I am playing around with your branch locally and am noticing some issues with connect/disconnect. If you are done with your implementation, I think it would be best to merge into a working branch rather than the `dev` branch so I can change the way we are handing that given the updates.

Let me know if this is still a work in progress or if it is ready to merge.

Thanks!

**Comment by jordaaash** [comment]
It's ready to merge! What are the issues with connecting/disconnecting though? Anything we need to be concerned about in the library?

**Comment by jordaaash** [comment]
I pushed some updates to this to include the latest Release Candidate of `@solana/wallet-adapter-react` and the latest version of `@solana-mobile/wallet-adapter-mobile`. Please let me know if your connect/disconnect issues persist!

**Comment by walt-1** [comment]
Because we are not using the autoConnect param, we build custom logic around maintaining wallet connection. Some of this needs to be refined so its likely on our side, not on the library. But if I find any problems, I will let you know.

**Comment by jordaaash** [comment]
Maybe don't merge yet, I'm reworking some things in the dependencies, will push a new version.

**Comment by jordaaash** [comment]
We're at RC 9, which looks likely to be the last RC. This PR updates GooseFX to use the latest RC. I'll follow up once we hit full release. There are no functional changes for apps with this update. It makes how wallets attach to the window more robust.

**Comment by walt-1** [comment]
@jordansexton - give a thumbs up if you are done and I will merge.

**Comment by jordaaash** [comment]
Yep, I'm done!

**Comment by steveluscher** [comment]
Hey! I think there's still a bug with mobile wallet adapter.

https://user-images.githubusercontent.com/13243/198368377-d8b5d732-c24e-4466-bae6-6147bad77880.mov

Are you, perchance, recreating the `SolanaMobileWalletAdapter` after connecting (eg. because memoization is getting busted?).

**Comment by steveluscher** [comment]
I'll fix this.

**Comment by billythedummy** [comment]
@steveluscher reporting another possible issue here: i don't get redirected to https://solanamobile.com/wallets when i click on the button with an android phone that has no wallet installed and seem to just get stuck on the loading state forever

Browser: firefox v99.2.0.

https://user-images.githubusercontent.com/12636708/198526781-37b774bc-75cb-4827-aaea-efe677c4fb80.mp4

On chrome v100.0.4896.127 the loading state disappears but nothing happens

**Pull request merged**
