### PR TITLE
sending events to node server and wrapperd up on analytics stats

### PR DESCRIPTION
**Pull request by candidatek**
## Types of changes

- [ ] Technical Debt (non-breaking change which removes unused code/assets)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] The related ClickUp task has been linked to this PR
- [ ] The person creating the pull request is listed in "Assignees"
- [ ] Change requires updated documentation

### CODE REVIEW

**Comment by usgoose** [comment]
Task linked: [CU-2q9pknj API and UI: Total Liquidity iin farm pool](https://app.clickup.com/t/2q9pknj)

**Review by walt-1 — APPROVED** [review]

**Comment by usgoose** [comment]
Task linked: [CU-2p1f0mq UI: Create a Boiler plate for Stats page](https://app.clickup.com/t/2p1f0mq)

**Comment by usgoose** [comment]
Task linked: [CU-2q9mqaf UI: GOFX number of holder](https://app.clickup.com/t/2q9mqaf)

**Comment by usgoose** [comment]
Task linked: [CU-2v6j76c GA4 Server Implementation](https://app.clickup.com/t/2v6j76c)

**Pull request merged**
